### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by LoadHack** [Possbl/R6S-External-V2#2]
I have a message that the pid and the bass have been found
And the insert menu does not open

**Comment by K-r-n-l** [comment]
You are doing something completely wrong then. 
I didn't have any problems with this base other than getting banned for being too obvious with aimbot after two days.
I've heard external vis checks are not possible on R6 so I will go internal.

On another note
1. It's outdated now. Update the decryptions. 
2. Change Overlay.
3. If you can't even figure out why the menu won't open good luck..

**Comment by Possbl** [comment]
> I have a message that the pid and the bass have been found
> 
> And the insert menu does not open

Seems like a driver issue if you're not using a driver and you're doing this offline, ensure that your get base address is returning the correct base and the pid is correct.

**Comment by kali-11ay** [comment]
how to update?
fr wasnt in siege for like 2 years now and the decryption is ass...

**Comment by kali-11ay** [comment]
Yes, I did and they all just said that you should learn the basics... not helpful

**Comment by Possbl** [comment]
> Yes, I did and they all just said that you should learn the basics... not helpful

Then you should probably learn the basics

**Comment by kali-11ay** [comment]
wow

**Comment by kali-11ay** [comment]
any1 should to a tutorial for the decrytion shit fr

**Comment by kali-11ay** [comment]
> > wow
> 
> Like I said, I cannot help you update it.
> 
> There are also countless reasons as to why I'm not.
> 
> 1. University takes most of my time
> 2. No point in updating as it's open source
> 3. Everything you need to update it, is public

send link "where its public"

**Comment by Possbl** [comment]
> any1 should to a tutorial for the decrytion shit fr

It isn't very confusing

**Comment by Possbl** [comment]
> > > wow
> 
> > 
> 
> > Like I said, I cannot help you update it.
> 
> > 
> 
> > There are also countless reasons as to why I'm not.
> 
> > 
> 
> > 1. University takes most of my time
> 
> > 2. No point in updating as it's open source
> 
> > 3. Everything you need to update it, is public
> 
> 
> 
> send link "where its public"

I said you can look on uc in the REVERSAL THREAD

**Comment by Possbl** [comment]
> https://www.unknowncheats.me/forum/rainbow-six-siege/255148-rainbow-six-siege-reversal-structs-offsets.html

Yes

**Comment by kzg77** [comment]
some one should make a vid on how to do this i have found so much cool stuff that i dont know how to use ):

**Comment by Possbl** [comment]
> 

hey bro, sorry to inform you that this was just meant as a fun project. Those that understand the code and understand how to use it may fully rightfully use it but other than that there will be no proper tutorial from me at least

**Comment by kzg77** [comment]
i want to get into using git hub could you teach me the basics one day if u have time i can pay yu its ok if not i understand
